alakantti/advertisement/models.py
# -*- coding: utf-8 -*-
"""Ad models."""
import datetime as dt

from alakantti.database import Column, Model, db, relationship, SurrogatePK

class Advertisemnt(Model, SurrogatePK):
    """An Advertisemtn."""

    __tablename__ = 'advertisement'
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    owner_id = Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    active = Column(db.Boolean(), default=False)
    
    earliest_start = Column(db.Date, nullable=False)
    latest_end = Column(db.Date, nullable=False)
    
    owner = db.relationship('User', backref=db.backref('advertisemnts', lazy=True))
        
    name = Column(db.String(124), nullable=False)
    budget = Column(db.Integer, nullable=False)
    
    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Advertisemnt({id!r})>'.format(id=self.id)
        

alakantti/advertisement/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm

from wtforms import IntegerField, StringField, DateField, SelectMultipleField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional
from wtforms.widgets import ListWidget, CheckboxInput

from datetime import date

from .models import Advertisemnt

class MultiCheckboxField(SelectMultipleField):
	widget = ListWidget(prefix_label=False)
	option_widget = CheckboxInput()


class AdvertisementForm(FlaskForm):
    """Register form."""

    name = StringField('Name', validators=[DataRequired(), Length(min=3, max=25)])
    budget = IntegerField('Budget', validators=[DataRequired()])
    
    earliest_start = DateField('Earliest Start', format='%d/%m/%Y', default=date(2018, 3, 19), validators=[DataRequired()])
    latest_end = DateField('Latest End', format='%d/%m/%Y', default=date(2018, 3, 25), validators=[DataRequired()])

    age_range_up = IntegerField('Age range Up', validators=[Optional()])
    age_range_low = IntegerField('Age range low', validators=[Optional()])
    
    gender = MultiCheckboxField('Gender', choices=[('M', 'Male'), ('F', 'Female')])
    
    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AdvertisementForm, self).__init__(*args, **kwargs)
        self.advertisemnt = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(AdvertisementForm, self).validate()
        if not initial_validation:
            return False
        return True
		
class AdvertisementOptimizationForm(FlaskForm):
	pass

alakantti/advertisement/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

alakantti/advertisement/views.py
# -*- coding: utf-8 -*-
"""User views."""
import datetime
import io
import csv
from datetime import timedelta
from itertools import zip_longest

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from alakantti.advertisement.models import Advertisemnt
from alakantti.advertisement.forms import AdvertisementForm, AdvertisementOptimizationForm
from alakantti.utils import flash_errors, daterange

from alakantti.lib.optimize import optimize_ad
from alakantti.providers.models import JCDEcauxOutdoor

from alakantti.lib.influx_client import *

blueprint = Blueprint('advertisement', __name__, url_prefix='/ads', static_folder='../static')


GRID_DATABASE = {
    'Columbus Helsinki': 6305076,
    'Linnanmäki Helsinki': 6094125,
    'Töölöntori Helsinki': 6075376,
    'Aleksanterinkatu Helsinki': 6098821,
    'Metroasema Aalto-yliopisto': 5976925,
}

INV_GRID_DATABASE = {v: k for k, v in GRID_DATABASE.items()}

@blueprint.route('/')
@login_required
def list_ads():
    """List ads."""
    return render_template('advertisement/list.html')


@blueprint.route('/create/', methods=['GET', 'POST'])
def create():
    """Register new ad."""
    form = AdvertisementForm(request.form)
    if form.validate_on_submit():
        ad = Advertisemnt.create(
            owner=current_user,
            name=form.name.data, 
            budget=form.budget.data,
            earliest_start=form.earliest_start.data,
            latest_end=form.latest_end.data,
            active=True)
            
        flash('Awesome, now lets optimise it!', 'success')
        return redirect(url_for('advertisement.optimize', ad_id=ad.id ))
    else:
        flash_errors(form)
    return render_template('advertisement/create.html', form=form)
    

@blueprint.route('/<ad_id>', methods=['GET', 'POST'])
def view(ad_id):
    """Register new user."""
    advertisemnt = Advertisemnt.get_by_id(ad_id)
    return render_template('advertisement/view.html', advertisemnt=advertisemnt)
    
    
@blueprint.route('/<ad_id>/performance', methods=['GET', 'POST'])
def performance(ad_id):
    """Register new user."""
    advertisemnt = Advertisemnt.get_by_id(ad_id)
    return render_template('advertisement/performance.html', advertisemnt=advertisemnt)


@blueprint.route('/<ad_id>/optimize', methods=['GET', 'POST'])
def optimize(ad_id):
    """Register new user."""
    advertisemnt = Advertisemnt.get_by_id(ad_id)
    
    start_date = advertisemnt.earliest_start
    end_date = advertisemnt.latest_end
    max_price = advertisemnt.budget
    
    optimization_results = optimize_ad(
        start_date,
        end_date,
        max_price)
        
    date_results_dict = {}
    
    for single_date in daterange(start_date, end_date):
        date_string = single_date.strftime("%A %d/%m/%Y")
        date_results_dict[date_string] = []
        
        for result in optimization_results:
            if result['date'].date() == single_date:
                date_results_dict[date_string].append(result)
    
    selected_points = set(x['name'] for x in optimization_results)
    grid_ids = set(GRID_DATABASE[x] for x in selected_points)
    
    cli = InfluxDBBackend()
    data_series = []
    headers = ["Time"]
    for grid_id in grid_ids:
        query = cli.get_metric_for_date_range(grid_id ,start_date-timedelta(days=5), start_date)
        if not query.items():
            continue
        headers += [INV_GRID_DATABASE[grid_id]]
        results = query.items()[0][1]
        new_data = [str(x['count']) for x in results]
        data_series.append(new_data)
    
    # Populate with timestamps
    query = cli.get_metric_for_date_range(grid_id ,start_date-timedelta(days=7), start_date)
    results = query.items()[0][1]
    # 2018-03-18T07:00:00Z"
    # DD-MM-YYYY HH:mm:ss
    data_series = [
        [
            datetime.datetime.strptime(
                x['time'], 
                "%Y-%m-%dT%H:%M:%SZ").isoformat() for x in results]
        
    ] + data_series
    
    export_data = zip_longest(*data_series, fillvalue = '')
    
    # output = io.StringIO()
    # writer = csv.writer(output, quoting=csv.QUOTE_NONNUMERIC)
    # writer.writerow(headers)
    # writer.writerows(export_data)
    # csv_string = output.getvalue()
    headers = [",".join(headers)]
    export_2 = [ ",".join(x) for x in export_data]
    
    datapoints = JCDEcauxOutdoor.get_all()
    
    # datapoints = []
    return render_template('advertisement/optimize.html', 
        export_data=list(headers + export_2),
        selected_points=selected_points,
        datapoints=datapoints, 
        date_results_dict=date_results_dict,
        advertisemnt=advertisemnt)

alakantti/templates/advertisement/create.html
{% extends "layout.html" %}
{% block content %}
<div class="container-narrow">
  <h1 class="mt-5">Optimize an advertisement campaign</h1>
    <br/>  
    <form id="advertisemntForm" class="form form-register" method="POST" action="" role="form">
           {{ form.csrf_token }}
            <h4>Basic information</h4>
            <div class="form-group">
               {{form.name.label}}
               {{form.name(placeholder="E.g. Black friday", class_="form-control")}}
            </div>
            <div class="form-group">
               {{form.earliest_start.label}}
               {{form.earliest_start(placeholder="19/03/2018", class_="form-control")}}
            </div>

            <div class="form-group">
               {{form.latest_end.label}}
               {{form.latest_end(placeholder="25/03/2018", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.budget.label}} (in EUR)
                {{form.budget(placeholder="100", class_="form-control")}}
            </div>
            
            <h4>Your target group</h4>
            <h5>(demographic optimization only available in the pro version :-)</h5>
            <div class="form-group">
                {{form.age_range_low.label}}
                {{form.age_range_low(placeholder="18", class_="form-control", disabled=true)}}
            </div>
            
            <div class="form-group">
                {{form.age_range_up.label}}
                {{form.age_range_up(placeholder="99", class_="form-control", disabled=true)}}
            </div>
            
            <div class="form-group">
                {{form.gender.label}}
                {{form.gender(disabled=true)}}
            </div>
        
            <p><input class="btn btn-primary" type="submit" value="Let's optimize!"></p>
    </form>
</div>
{% endblock %}

alakantti/templates/advertisement/list.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">Your advertisements</h1>
        
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Created at</th>
              <th scope="col">Campaign name</th>
              <th scope="col">Earliest Start</th>
              <th scope="col">Latest end</th>
              <th scope="col">Budget</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          
          <tbody>
            {% for ad in current_user.advertisemnts %}
              <tr>
                <td>{{ad.created_at.strftime('%Y-%m-%d')}}</td>
                <td>{{ad.name}}</td>
                <td>{{ad.earliest_start}}</td>
                <td>{{ad.latest_end}}</td>
                <td> <h5>{{ad.budget}}€</h5></td>
                <td>
                  <a class="btn btn-primary btn-sm" href="{{ url_for('advertisement.view', ad_id=ad.id) }}" role="button">
                    <i class="fa fa-eye"></i>View
                  </a>
                  <a class="btn btn-primary btn-sm" href="{{ url_for('advertisement.optimize', ad_id=ad.id) }}" role="button">
                    <i class="fa fa-line-chart"></i>
                    Optimize
                  </a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <a class="btn btn-primary" href="{{ url_for('advertisement.create')}}" role="button">
          <i class="fa fa-plus-circle"></i>
          New Advertisement
        </a>
    </div>
{% endblock %}

alakantti/templates/advertisement/optimize.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
  integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
  crossorigin=""/>
  
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
  integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
  crossorigin=""></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dygraph.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dygraph.min.css" />

<div class="container">
  <h1 class="mt-5">Advertisement optimization</h1>
  <br/>
  <div class="row">
    <div class="col-sm">
      <h5> Selected Locations</h5>
      <div id="mapid"></div>
    </div>
    <div class="col col-lg-5">
      <h5> Selected outdoors the previous week</h5>
      <div id="graphdiv"></div>
    </div>
  </div>
  <div class="row">
    <h3 class="mt-5"> Your advertisement breakdown</h3>
    <div class="table-responsive">
      <table class="table">
        <tbody>
          {% for key, value in date_results_dict.items() %}
          <tr>
            <td scope="row"> {{key}} </td>
            <td> 
              
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Location</th>
                    <th scope="col">Time</th>
                    <th scope="col">People flow</th>
                    <th scope="col">Price</th>
                  </tr>
                </thead>
                <tbody>
                  {% for ad in value %}
                  <tr>
                      <td>{{ad['name']}}</td>
                      <td>{{ad['time']}}</td>
                      <td>{{ad['footfall_count']}}</td>
                      <td>{{ad['price']}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </td>
          <tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
    var mymap = L.map('mapid').setView([60.1672247, 24.9399874], 11);
    L.tileLayer(
      'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21haXNpZG9ybyIsImEiOiJjajhvdGhvaXUwN2h4MndyczAzczFxZXZvIn0.wnkeyFU8IGuG6ANNj_Abig', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox.streets',
      accessToken: 'your.mapbox.access.token'
    }).addTo(mymap);
    

    {% for datapoint in datapoints %}
       var opacity = {{ 1 if datapoint.name in selected_points else 0.3}}
       var marker = L.marker(
          [
            {{datapoint.latitude}}, 
            {{datapoint.longitude}}],
            {'opacity': opacity}
        ).addTo(mymap);
        
       marker.bindPopup("{{datapoint.name}}")
    {% endfor %}
</script>


<script type="text/javascript">
  
  var data = ""
   {% for x in export_data %}
   data = data + "{{x}}\n"
   {% endfor %}
  
   new Dygraph(
         document.getElementById("graphdiv"),
         data,
         { 
           xAxisLabelWidth: 80,
           axisLabelFontSize: 12,
           xValueFormatter: Dygraph.dateString_,
            xValueParser: function(x) { 
                var d = new Date(x)
                return d.getTime();
            },
        }
       );
</script>


{% endblock %}

alakantti/templates/advertisement/performance.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">Your advertisemnt {{advertisemnt.name}}</h1>
        <table>
          
        </table>
    </div>
{% endblock %}

alakantti/templates/advertisement/view.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">Your advertisemnt {{advertisemnt.name}}</h1>
          
        </table>
    </div>
{% endblock %}